version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: n8n-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: supabase_auth,supabase_storage,supabase_realtime
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/01-init-multiple-databases.sh
      - ./init-auth-schema.sql:/docker-entrypoint-initdb.d/02-init-auth-schema.sql
      - ./init-storage-schema.sql:/docker-entrypoint-initdb.d/03-init-storage-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - n8n-network

  supabase-kong:
    image: kong:2.8.1
    container_name: supabase-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./supabase/kong.yml:/kong.yml
    depends_on:
      - supabase-auth
    networks:
      - n8n-network

  supabase-auth:
    image: supabase/gotrue:v2.100.0
    container_name: supabase-auth
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/supabase_auth
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
      GOTRUE_SMTP_HOST: localhost
      GOTRUE_SMTP_PORT: 587
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_SENDER_NAME: ""
      GOTRUE_MAILER_URLPATHS_INVITE: http://localhost:3000/auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: http://localhost:3000/auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: http://localhost:3000/auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: http://localhost:3000/auth/v1/verify
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n-network

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    container_name: supabase-rest
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/n8n
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_LOG_LEVEL=info
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - SUPABASE_URL=http://supabase-kong:8000
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "5678:5678"
    volumes:
      # CONFIGURACIÓN PRINCIPAL - Datos de n8n
      - n8n_data:/home/node/.n8n
      
      # MAPEO DE ARCHIVOS LOCALES - ¡NUEVA CONFIGURACIÓN!
      # Mapea tu carpeta de workflows local al contenedor
      - ./workflows:/home/node/.n8n/workflows-local:ro
      
      # Mapea carpetas específicas para acceso bidireccional
      - ./workflows/local_n8n:/home/node/.n8n/local-workflows
      - ./workflows/exports:/home/node/.n8n/exports
      
      # Directorio para archivos generados por los agentes
      - ./data/research-reports:/home/node/.n8n/research-reports
      - ./data/generated-files:/home/node/.n8n/generated
      - ./data/temp:/home/node/.n8n/temp
      
      # Logs accesibles localmente
      - ./logs:/home/node/.n8n/logs
      
      # Configuraciones personalizadas
      - ./configs:/home/node/.n8n/configs:ro
    depends_on:
      postgres:
        condition: service_healthy
      supabase-auth:
        condition: service_started
    networks:
      - n8n-network

volumes:
  postgres_data:
  n8n_data:
  storage_data:

networks:
  n8n-network:
    driver: bridge